version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket wallet.lambda
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml