AWSTemplateFormatVersion: '2010-09-09'
Description: Handle wallet operations
Resources:
  ApiGatewayApi:
    Properties:
      DefinitionUri: s3://wallet.lambda/d878f0009ff46b6963868c5f5dca5880
      StageName: v1
      Variables:
        CreateFunctionName:
          Ref: CreateFunction
        ListFunctionName:
          Ref: ListFunction
    Type: AWS::Serverless::Api
  CreateFunction:
    Properties:
      CodeUri: s3://wallet.lambda/ba386b470e33e22beb7f6c94678f091e
      Events:
        DefaultApi:
          Properties:
            Method: POST
            Path: /wallet
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: main.create
      Runtime: python3.6
    Type: AWS::Serverless::Function
  ListFunction:
    Properties:
      CodeUri: s3://wallet.lambda/ba386b470e33e22beb7f6c94678f091e
      Events:
        DefaultApi:
          Properties:
            Method: GET
            Path: /wallet
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: main.list
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
