AWSTemplateFormatVersion: '2010-09-09'
Description: Handle wallet operations
Parameters:
  DBMasterPassword:
    Default: WalletDBMasterPassword
    Type: AWS::SSM::Parameter::Value<String>
  DBMasterUserName:
    Default: WalletDBMasterUserName
    Type: AWS::SSM::Parameter::Value<String>
  DBName:
    Default: WalletDBName
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  ApiGatewayApi:
    Properties:
      DefinitionUri: s3://wallet.lambda/a29a67865311089c72609bfc6b23c975
      StageName: v1
      Variables:
        CreateFunctionName:
          Ref: CreateFunction
        DeleteFunction:
          Ref: DeleteFunction
        ListFunctionName:
          Ref: ListFunction
    Type: AWS::Serverless::Api
  CreateFunction:
    Properties:
      CodeUri: s3://wallet.lambda/d70c5c3972ee11b5519911492a326796
      Environment:
        Variables:
          DB_ENDPOINT_ADDRESS:
            Fn::GetAtt:
            - WalletDB
            - Endpoint.Address
          DB_NAME:
            Ref: DBName
          DB_PASSWORD:
            Ref: DBMasterPassword
          DB_PORT:
            Fn::GetAtt:
            - WalletDB
            - Endpoint.Port
          DB_USERNAME:
            Ref: DBMasterUserName
      Events:
        DefaultApi:
          Properties:
            Method: POST
            Path: /wallet
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: main.create
      Runtime: python3.6
    Type: AWS::Serverless::Function
  DbSecurityByEC2SecurityGroup:
    Properties:
      DBSecurityGroupIngress:
      - CIDRIP: 0.0.0.0/0
      GroupDescription: Ingress for Amazon EC2 security group
    Type: AWS::RDS::DBSecurityGroup
  DeleteFunction:
    Properties:
      CodeUri: s3://wallet.lambda/d70c5c3972ee11b5519911492a326796
      Environment:
        Variables:
          DB_ENDPOINT_ADDRESS:
            Fn::GetAtt:
            - WalletDB
            - Endpoint.Address
          DB_NAME:
            Ref: DBName
          DB_PASSWORD:
            Ref: DBMasterPassword
          DB_PORT:
            Fn::GetAtt:
            - WalletDB
            - Endpoint.Port
          DB_USERNAME:
            Ref: DBMasterUserName
      Events:
        DefaultApi:
          Properties:
            Method: DELETE
            Path: /wallet/{uuid}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: main.delete
      Runtime: python3.6
    Type: AWS::Serverless::Function
  ListFunction:
    Properties:
      CodeUri: s3://wallet.lambda/d70c5c3972ee11b5519911492a326796
      Environment:
        Variables:
          DB_ENDPOINT_ADDRESS:
            Fn::GetAtt:
            - WalletDB
            - Endpoint.Address
          DB_NAME:
            Ref: DBName
          DB_PASSWORD:
            Ref: DBMasterPassword
          DB_PORT:
            Fn::GetAtt:
            - WalletDB
            - Endpoint.Port
          DB_USERNAME:
            Ref: DBMasterUserName
      Events:
        DefaultApi:
          Properties:
            Method: GET
            Path: /wallet
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: main.list
      Runtime: python3.6
    Type: AWS::Serverless::Function
  WalletDB:
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      DBName:
        Ref: DBName
      DBSecurityGroups:
      - Ref: DbSecurityByEC2SecurityGroup
      Engine: MySQL
      MasterUserPassword:
        Ref: DBMasterPassword
      MasterUsername:
        Ref: DBMasterUserName
    Type: AWS::RDS::DBInstance
Transform: AWS::Serverless-2016-10-31
