AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handle wallet operations
Resources:
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.list
      Runtime: python3.6
      CodeUri: ./
      Events:
        DefaultApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /wallet
            Method: GET
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.create
      Runtime: python3.6
      CodeUri: ./
      Events:
        DefaultApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /wallet
            Method: POST
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yaml
      StageName: v1
      Variables:
        ListFunctionName: !Ref ListFunction
        CreateFunctionName: !Ref CreateFunction

#  Database:
#    Type: AWS::RDS::DBInstance
#    Properties:
#      DBSecurityGroups:
#      - Ref: sg-1825567f
#      AllocatedStorage: '5'
#      DBInstanceClass: db.m1.micro
#      Engine: MySQL
#      MasterUsername: MyName
#      MasterUserPassword: MyPassword
#    DeletionPolicy: Snapshot
